creation of the flask project
codeJunctionTeam/fire-call pull request #2
Opened 2019-12-13 19:22 UTC by rajitha1998

## Changes proposed in the pull request
  * Creating a flask project
## Impact
  *  Overall Application

2019-12-13 19:23 UTC, rajitha1998 commented
Review required @janethavi @hasalfernando @nandulaperera @Purushothh

2019-12-14 04:11 UTC, hasalfernando approved these changes

2019-12-14 04:11 UTC, hasalfernando approved these changes

2019-12-14 04:12 UTC, hasalfernando approved these changes

2019-12-14 05:04 UTC, janethavi requested changes
@rajitha1998 Can you please add these files/folders(app.py,static/,templates/)  to a separate parent folder called "api"

2019-12-14 05:06 UTC, rajitha1998 commented
> @rajitha1998 Can you please add these files/folders(app.py,static/,templates/) to a separate parent folder called "api"

sure :)

2019-12-14 06:08 UTC, janethavi requested changes

2019-12-14 06:08 UTC, janethavi commented on .gitignore
> +api/*.py[cod]
@rajitha1998 Can you please add an EOF?

2019-12-14 06:08 UTC, hasalfernando approved these changes

2019-12-14 06:23 UTC, janethavi approved these changes

2019-12-14 06:24 UTC, merged